version: '2.4'
services:
  contact_discovery_service:
    build: ./docker
    container_name: contact_discovery_service
    restart:        always
    privileged: true
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
      - /dev/isgx
    ports:
      - 9090:9090
    volumes:
      - .:/opt/contact_discovery_service
      - ../CDS_config.yml:/opt/CDS_config.yml
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
    network_mode: "host"
    command: sh -c ./start.sh
    working_dir: /opt/contact_discovery_service
    logging:
      options:
        max-size: "120k"
        max-file: "3"
