name: enclave
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  make_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/enclave
        with:
          target: test

